### ISSUE TITLE
Panel notification doesn't work

### ISSUE THREAD

**Issue by maltewassermann** [rasteiner/kirbytranslations#12]
Fix:

**static-translations.php**
`return panel()->notify(':)');` instead of `self::->notify(':)');`

**views/index.php**
`… then(function(response) { window.location.reload(); });`

**Comment by rasteiner** [comment]
Thanks :)

addressed in https://github.com/rasteiner/kirbytranslations/commit/c3a40dc8a2cf7f60de58190f6e5c31221e49bc34
