### ISSUE TITLE
Undefined index: default

### ISSUE THREAD

**Issue by illycz** [rasteiner/kirbytranslations#13]
I'm trying your plugin within fresh https://github.com/getkirby/langkit installation (Kirby 2.5.7) and I get `Undefined index: default` error on translations page in panel.

Thanks for any suggestion...

**Comment by rasteiner** [comment]
I'm currently away from my workstation... could you checkout [this branch](https://github.com/rasteiner/kirbytranslations/tree/fix-%2313) and see if the solves the problem? 

You can download it as zip here: https://github.com/rasteiner/kirbytranslations/archive/fix-%2313.zip

Thx :)

**Comment by illycz** [comment]
`Undefined index: date.format`
And first string:

![image](https://user-images.githubusercontent.com/2109984/33612658-93e2a8e6-d9d2-11e7-8eb8-7db912f562ab.png)

**Comment by rasteiner** [comment]
Ok, I didn't see those because on my machine PHP Notices aren't shown. 
Now the master branch should work. 

Thanks :)

**Comment by illycz** [comment]
But I have more strings in locale files...

**Comment by rasteiner** [comment]
Did you try the latest version? 
https://github.com/rasteiner/kirbytranslations/archive/master.zip

**Comment by illycz** [comment]
It's working now. Thanks
