### ISSUE TITLE
[Bug] l::set in only one language file

### ISSUE THREAD

**Issue by mxub** [rasteiner/kirbytranslations#4]
I just installed the langkit and then the static-translations plugin (via CLI)

it the says: 

> Undefined index: en

## The Problem

I found the Problem. It is, that there is one `l::set('pagination.prev')` in de.php that is not in en.php

## Possible Solution

Build all `l::set` from the default language and set the unset names in other languages to empyt

**Comment by rasteiner** [comment]
Merged the pr
